name: Tests

on: [push]

jobs:
  cypress-run:
    name: Webnative ${{ matrix.webnative }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome89-ff86
    strategy:
      matrix:
        webnative:
          - latest
          - alpha
          - 0.23.2
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: ğŸ”‘ Get cache directory
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"
      - name: ğŸ’¾ Cache modules
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            ~/.cache/Cypress
            ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: ğŸ§ª Run tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm start
          wait-on: "http://localhost:8080"
      - name: ğŸº Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
        env:
          CYPRESS_WEBNATIVE: ${{ matrix.webnative }}